### ISSUE TITLE
unrecognized intrinsic function: `return_address`

### ISSUE THREAD

**Issue by k0pernicus** [intermezzOS/libcore#2]
Hi,

I'm trying to implement my own operating system using this wonderful project.  
I run it using the `nightly` version of Rust (rustc 1.12.0-nightly (27e766d7b 2016-07-19)), and I've got a compiler error when I try to build the project:
```
$ cargo build --release --features disable_float --target=x86_64-unknown-aros-gnu.json
   Compiling core v0.0.0 (file:///Users/antonin/Documents/dev/aros/build/libcore)
intrinsics.rs:300:5: 300:45 error: unrecognized intrinsic function: `return_address` [E0093]
intrinsics.rs:300     pub fn return_address<T>() -> *const u8;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
intrinsics.rs:300:5: 300:45 help: run `rustc --explain E0093` to see a detailed explanation
error: aborting due to previous error
error: Could not compile `core`.

To learn more, run the command again with --verbose.
```

Is there any problem using this library?

**Comment by k0pernicus** [comment]
I think that `libcore` is not updated for this `nightly` version of Rust, right?

**Comment by steveklabnik** [comment]
Yes, you must use _exacty_ the nightly that's in the kernel's README.

**Comment by k0pernicus** [comment]
Oh crap - miss that...  
Sorry for that mistake :-/

**Comment by steveklabnik** [comment]
No worries!

I periodically update it, but since I have to do it by hand, I don't do it too regularly.

**Comment by k0pernicus** [comment]
I don't know how to do that, but I can help you if you have some "rules" to follow to do that :-)
